### ISSUE TITLE
export as pdf and unit

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3Exporters#2]
@pavel-krivanek said:
> we can set the paper size by setting the canvas size but the ratio is somehow strange. 100 units = 1.398" = 35.5092 mm. More explicit and clean units management would be nice.

**Comment by akevalion** [comment]
@pavel-krivanek how can I have that values? I have a canvas `500@500` what is the expected result? to handle that?

```Smalltalk
canvas pdfExporter fileName: 'test'; export
```
What is the correct size for `test.pdf`?

Because the info, resolution is `500x500`
![image](https://user-images.githubusercontent.com/10532890/84855915-4ffca700-b033-11ea-8677-f07b1bb61d9d.png)

**Comment by pavel-krivanek** [comment]
The PPI value should be configurable, as default value I would select standard 96 PPI. So 132.291667 millimeters in this case.

**Comment by akevalion** [comment]
What is ppi?

**Comment by akevalion** [comment]
Roassal exporters now use https://github.com/zweidenker/Units
Consider the following script with the last version of Roassal3Exporters

```Smalltalk
c := RSCanvas new.

lbls := RSGroup new.
Collection withAllSubclassesDo: [ :cls |
    lbl := RSLabel new text: cls name; model: cls.
    lbls add: lbl ].
c addAll: lbls.

RSNormalizer fontSize
    shapes: lbls;
    normalize: #numberOfMethods.
    
"RSHierarchyPacker  on: lbls."
c @ RSCanvasController.
c @ RSHierarchyPacker.

c extent: (RSPageExtent from: 8.26 inches@ 11.69 inches).
c pdfExporter
	fileName: 'test';
	export.
```

![image](https://user-images.githubusercontent.com/10532890/84969265-5861ea00-b0e6-11ea-857f-00306ab47def.png)

RSPDFExporter uses unit `point` to export and create the pdf file. 1 point = 1/72 inch
You will need to change the canvas extent in order to create a pdf document.

Use RSPageExtent, to correctly set the canvas extent before the export process.
You can access a default values for well known pages sizes.
`RSPageExtent letter` or `RSPageExtent a4`.

What do you think about it?

**Comment by pavel-krivanek** [comment]
PPI = pixels per inch. 
Very nice, it would be actually great to support the units even on the canvas level so you could draw lines with explicit extents in millimetres (for example) without need to recompute. 

From where the value 72 comes from?

**Comment by akevalion** [comment]
It is an standard, I think we can not use units in roassal, because of the camera, with roassal camera you can adjust your visualization to the desire size.

Then is better use units in the canvas extent instead of each shape's coordinates

https://cairographics.org/manual/cairo-PDF-Surfaces.html#cairo-pdf-surface-create

**Comment by tinchodias** [comment]
I was also curious about the 1/72 and found interesting info in [this wiki page](https://en.wikipedia.org/wiki/Point_(typography)). 

May be not useful for the discussion, but I can add what I understand from the low-level PDF Cairo surface: The function caller always implicitly uses such 1/72 inch points. 

For example, if you want to create an horizontal line of 1 inch in a A4 page, you can do this:
* create the surface with extent of 595 @ 842 (an A4 page according to [this spec](https://www.prepressure.com/library/paper-size#ANSI))
* draw a line from 10@10 to (10+72)@10 (because 72 points = 1 inch).
However, if you want to use more intuitive numbers at the moment of drawing, you have the possibility to apply some scale transformation before drawing.

Well, I hope it doesn't darkens more than it cleans.

**Comment by akevalion** [comment]
Roassal3 PDF now uses units, can we close this issue?
