### ISSUE TITLE
Debug: Instance of RSConfigurableCamera did not understand #matrix

### ISSUE THREAD

**Issue by tsl4** [ObjectProfile/Roassal3Exporters#39]
Running the example code (and any other similar code) results in that debug message. There does not seem to be a #matrix method on RSConfigurableCamera

![Screen Shot 2023-05-18 at 08 55 10](https://github.com/ObjectProfile/Roassal3Exporters/assets/9586238/44ed70f2-f77d-4083-b588-02b07b9d66ca)

**Comment by tsl4** [comment]
I did try simply commenting out that line, and it does seem to work. Not really understanding what 'matrix' was or used to be in this contest.

**Comment by JanBliznicenko** [comment]
This seems like a mismatch between version of Roassal3 and Roassal3Exporters. RSAbstractCamSetter>>#set: was changed on April (by me to fix RSCamSetter making changes to your canvas instead of only the expoted copy) and it only works with Roassal3 from February 22 or later.
If you loaded latest commit from master of Roassal3Exporters, you should also have lastest commit from master of Roassal3.
To use older commits of Roassal3 (like the one that is part of Pharo itself), you should probably use numbered release of Roassal3Exporters.

**Comment by akevalion** [comment]
Hi RSConfigurableCamera is subclass of RSCamera and camera has matrix selector.
